/// <reference path="Communication" />
/// <reference path="Repliq" />
/// <reference path="RepliqManager" />
/// <reference path="RepliqData" />
/// <reference path="Operation" />
/// <reference path="Round" />
/// <reference path="Types" />
/// <reference path="protocols/Register" />
/// <reference path='../../node_modules/immutable/dist/Immutable.d.ts'/>