/// <reference path="client/index" />
/// <reference path="server/index" />
/// <reference path="shared/Repliq" />
var index_1 = require("./client/index");
exports.RepliqClient = index_1.RepliqClient;
var index_2 = require("./server/index");
exports.RepliqServer = index_2.RepliqServer;
var Repliq_1 = require("./shared/Repliq");
exports.define = Repliq_1.define;
//# sourceMappingURL=index.js.map